name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - run: npm ci

    - name: Build
      run: npm run build

    - run: npm run test

  deploy:
    name: "Deploy to Heroku"
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "itszoessite"
          heroku_email: "carl@tornqv.ist"
          dontautocreate: true
